---
apiVersion: v1
kind: Namespace
metadata:
  name: project-cloud-arch
  labels:
    name: project-cloud-arch

---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    name: jenkins

---
apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq

