{{- if not .Values.consumer.rabbitmqSecret.secretFromExisitng.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secret
type: Opaque
data:
  rabbitmq_username: {{ .Values.consumer.rabbitmqSecret.rabbitmqUsername | b64enc }}  
  rabbitmq_password: {{ .Values.consumer.rabbitmqSecret.rabbitmqPassword | b64enc }}  
  rabbitmq_host: {{ .Values.consumer.rabbitmqSecret.rabbitmqHost | b64enc }}  
  rabbitmq_port: {{ .Values.consumer.rabbitmqSecret.rabbitmqPort | b64enc }}  
{{- end }}
