{{- if .Values.serviceMonitor.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rabbitconsumer.fullname" . }}
  labels:
    {{- include "rabbitconsumer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "rabbitconsumer.selectorLabels" . | nindent 6 }}
  endpoints:
    - interval: 30s
      port: http
{{- end -}}
